name: Build and deploy
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Copy index html
        run: |
          mkdir -p build
          cp -r index.html build

      - name: Install dependencies and build 00_interactive-rating-component-main
        run: |
          cd 00_interactive-rating-component-main
          mkdir -p ../build/00_interactive-rating-component-main
          cp -r index.html ../build/00_interactive-rating-component-main
          cp -r main.js ../build/00_interactive-rating-component-main
          cp -r style.css ../build/00_interactive-rating-component-main
          cp -r images/ ../build/00_interactive-rating-component-main
  
      - name: Install dependencies and build 01-product-preview-card-component
        run: |
          cd 01-product-preview-card-component
          npm install
          npm run build
          mkdir -p ../build/01-product-preview-card-component
          cp -r dist ../build/01-product-preview-card-component
      
      - name: Install dependencies and build 02-skilled-e-learning-landing-page
        run: |
          cd 02-skilled-e-learning-landing-page
          npm install
          npm run build
          mkdir -p ../build/02-skilled-e-learning-landing-page
          cp -r dist ../build/02-skilled-e-learning-landing-page

      - name: Install dependencies and build 03-results-summary-component
        run: |
          cd 03-results-summary-component
          npm install
          npm run build
          mkdir -p ../build/03-results-summary-component
          cp -r dist ../build/03-results-summary-component
      
      - name: Install dependencies and build 04-tech-book-club-landing-page
        run: |
          cd 04-tech-book-club-landing-page
          npm install
          npm run build
          mkdir -p ../build/04-tech-book-club-landing-page
          cp -r dist ../build/04-tech-book-club-landing-page

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
